version: 2
jobs:
  build:
    working_directory: ~/test_project/dashboard
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/node:8.11.3-browsers
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    
  deploy-dev:
    working_directory: ~/test_project/dashboard
    parallelism: 1
    shell: /bin/bash --login
    steps:
      - checkout
      - run:
          name: Deploy TestDev
          command: |
            echo "-----------------------------------------------------------------------------------------"
  
  
workflows:
  version: 2
  build-and-deploy-dev:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop