version: 2.0

jobs:
  "trigger":
    docker:
      - image: circleci/python:3.7.4-stretch
    working_directory: ~/circleci-trigger-demo
    steps:
      - checkout
      - run:
          name: "Run Functional Tests"
          command: |
            curl -X POST \
            --header "Content-Type:application/json" \
            --data '{}' \
            "https://circleci.com/api/v1.1/project/github/$ORGANIZATION/$PROJECT/build?circle-token=$CIRCLE_TOKEN&revision=$BRANCH"

workflows:
  version: 2
  build:
    jobs:
      - "trigger"